- name: creating database
  mysql_db:
    name: "{{ db_name }}"
    state: "present"
    login_user: "root"
    login_password: "{{ mysql_root_password }}"

- name: creating database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: "%"
    priv: "{{ db_name }}.*:ALL"
    state: "present"
    login_user: "root"
    login_password: "{{ mysql_root_password }}"

- name: get database template
  template:
    src: wp-db.sql
    dest: /tmp/wp-db.sql

- name: Import Database
  mysql_db: name={{db_name}} login_user={{db_user}} login_password={{db_password}} state=import target=/tmp/wp-db.sql
