#---
# This playbook would deploy server-03.

- hosts: server-03
  user: vagrant
  become: yes
  vars:
    jenkins_hostname: server-03
  roles:
    - { role: sw-apt-mirror }
    - { role: nginx-jenk }
    - { role: jenkins }
