#---
# This playbook would deploy server-01.

- hosts: server-02
  user: vagrant
  become: yes
  vars:
    - mysql_root_password: "123QaZxSw123"
    - domain: "example.com"
    - download_url: "http://wordpress.org/latest.tar.gz"
    - wpdirectory: "/var/www"
    - db_name: "wordpress"
    - db_user: "wordpress"
    - db_password: "wordpress"
  roles:
#  - { role: common }
  - { role: mysql }
  - { role: wp-db }
