#---
# This playbook would deploy server-01.

- hosts: server-01
  user: vagrant
  become: yes
  vars:
    - mysql_root_password: "123QaZxSw123"
    - domain: "server-01"
    - download_url: "http://wordpress.org/latest.tar.gz"
    - wpdirectory: "/var/www"
    - db_host: "server-02"
    - db_name: "wordpress"
    - db_user: "wordpress"
    - db_password: "wordpress"
  roles:
  - { role: nginx }
  - { role: memcached }
  - { role: php7 }
  - { role: wp-site }
